//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int id { get; set; }
        public string Fio { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Post { get; set; }
    
        public virtual WorkerLogin WorkerLogin { get; set; }
    }
}
